"""Initial schema for Neon DB

Revision ID: 5a73a48a56b6
Revises: 
Create Date: 2026-09-13 19:00:11.547026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a73a48a56b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('insurer_name', sa.String(length=200), nullable=False),
    sa.Column('policy_type', sa.String(length=100), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_policies_id'), 'commercial_policies', ['id'], unique=False)
    op.create_index(op.f('ix_commercial_policies_policy_number'), 'commercial_policies', ['policy_number'], unique=True)
    op.create_table('common_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('terminology_system', sa.String(length=100), nullable=True),
    sa.Column('terminology_code', sa.String(length=100), nullable=True),
    sa.Column('terminology_display', sa.String(length=300), nullable=True),
    sa.Column('terminology_version', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_codes_common_code'), 'common_codes', ['common_code'], unique=True)
    op.create_index(op.f('ix_common_codes_id'), 'common_codes', ['id'], unique=False)
    op.create_table('fwa_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_index(op.f('ix_fwa_rules_id'), 'fwa_rules', ['id'], unique=False)
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_code', sa.String(length=20), nullable=False),
    sa.Column('hospital_name', sa.String(length=200), nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('response_endpoint', sa.String(length=500), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_hospital_code'), 'hospitals', ['hospital_code'], unique=True)
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_reference', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.DateTime(timezone=True), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('insurance_reference', sa.String(length=100), nullable=True),
    sa.Column('synthetic_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_patient_reference'), 'patients', ['patient_reference'], unique=True)
    op.create_table('terminology_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminology_systems_id'), 'terminology_systems', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('coverage_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('common_code_id', sa.Integer(), nullable=False),
    sa.Column('coverage_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('copay_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('requires_preauth', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['common_code_id'], ['common_codes.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['commercial_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_rules_id'), 'coverage_rules', ['id'], unique=False)
    op.create_table('facility_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_facility_users_id'), 'facility_users', ['id'], unique=False)
    op.create_table('hospital_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('hospital_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('synthetic_demo', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'hospital_code', name='uq_hospital_code')
    )
    op.create_index(op.f('ix_hospital_codes_id'), 'hospital_codes', ['id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_number', sa.String(length=100), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('relationship_to_principal', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['commercial_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_index(op.f('ix_members_member_number'), 'members', ['member_number'], unique=True)
    op.create_table('price_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_code_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_price', sa.Float(), nullable=False),
    sa.Column('allowed_variance_percent', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['common_code_id'], ['common_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_benchmarks_id'), 'price_benchmarks', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_reference', sa.String(length=100), nullable=False),
    sa.Column('submitted_amount', sa.Float(), nullable=False),
    sa.Column('normalized_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'transaction_id', name='uq_hospital_transaction')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_table('adjudications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('his_delivery_status', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_adjudications_id'), 'adjudications', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(length=100), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('total_billed_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_approved_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_patient_responsibility', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('service_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['commercial_policies.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=True)
    op.create_index('ix_claims_hospital_created', 'claims', ['hospital_id', 'created_at'], unique=False)
    op.create_index('ix_claims_hospital_status', 'claims', ['hospital_id', 'status'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_table('code_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('hospital_code_id', sa.Integer(), nullable=False),
    sa.Column('common_code_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mapping_status', sa.String(length=20), nullable=False),
    sa.Column('mapping_method', sa.String(length=50), nullable=True),
    sa.Column('mapped_by', sa.String(length=100), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['common_code_id'], ['common_codes.id'], ),
    sa.ForeignKeyConstraint(['hospital_code_id'], ['hospital_codes.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'hospital_code_id', name='uq_mapping')
    )
    op.create_index(op.f('ix_code_mappings_id'), 'code_mappings', ['id'], unique=False)
    op.create_table('fwa_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fwa_results_id'), 'fwa_results', ['id'], unique=False)
    op.create_table('integration_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_events_id'), 'integration_events', ['id'], unique=False)
    op.create_table('transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('hospital_code', sa.String(length=50), nullable=False),
    sa.Column('common_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('benchmark_price', sa.Float(), nullable=True),
    sa.Column('benchmark_status', sa.String(length=20), nullable=True),
    sa.Column('mapping_status', sa.String(length=20), nullable=True),
    sa.Column('mapping_confidence', sa.Float(), nullable=True),
    sa.Column('allowed_maximum', sa.Float(), nullable=True),
    sa.Column('variance_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_items_id'), 'transaction_items', ['id'], unique=False)
    op.create_table('claim_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('hospital_code_id', sa.Integer(), nullable=True),
    sa.Column('common_code_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('billed_unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('billed_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('approved_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('patient_responsibility', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['common_code_id'], ['common_codes.id'], ),
    sa.ForeignKeyConstraint(['hospital_code_id'], ['hospital_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_items_claim_id'), 'claim_items', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_items_id'), 'claim_items', ['id'], unique=False)
    op.create_table('external_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('claim_id IS NOT NULL OR transaction_id IS NOT NULL', name='ck_external_operation_owner'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'operation', 'idempotency_key', name='uq_external_operation_identity')
    )
    op.create_index(op.f('ix_external_operations_id'), 'external_operations', ['id'], unique=False)
    op.create_index(op.f('ix_external_operations_idempotency_key'), 'external_operations', ['idempotency_key'], unique=False)
    op.create_table('background_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('external_operation_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_classification', sa.String(length=100), nullable=True),
    sa.Column('worker_id', sa.String(length=200), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['external_operation_id'], ['external_operations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_background_jobs_ext_op_id', 'background_jobs', ['external_operation_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_id'), 'background_jobs', ['id'], unique=False)
    op.create_index('ix_background_jobs_status_next', 'background_jobs', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_background_jobs_transaction_id', 'background_jobs', ['transaction_id'], unique=False)
    op.create_table('external_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_operation_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('response_metadata', sa.JSON(), nullable=True),
    sa.Column('error_classification', sa.String(length=100), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['external_operation_id'], ['external_operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_operation_id', 'attempt_number', name='uq_external_attempt_number')
    )
    op.create_index(op.f('ix_external_attempts_id'), 'external_attempts', ['id'], unique=False)
    op.create_table('external_attempt_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_attempt_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['external_attempt_id'], ['external_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_attempt_events_id'), 'external_attempt_events', ['id'], unique=False)
    op.create_table('external_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_operation_id', sa.Integer(), nullable=False),
    sa.Column('external_attempt_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider_outcome', sa.String(length=50), nullable=True),
    sa.Column('provider_reference', sa.String(length=200), nullable=True),
    sa.Column('lookup_key', sa.String(length=200), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_classification', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['external_attempt_id'], ['external_attempts.id'], ),
    sa.ForeignKeyConstraint(['external_operation_id'], ['external_operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_operation_id', 'reconciliation_number', name='uq_external_reconciliation_number')
    )
    op.create_index('ix_external_reconciliations_ext_attempt_id', 'external_reconciliations', ['external_attempt_id'], unique=False)
    op.create_index('ix_external_reconciliations_ext_op_status', 'external_reconciliations', ['external_operation_id', 'status'], unique=False)
    op.create_index(op.f('ix_external_reconciliations_id'), 'external_reconciliations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_reconciliations_id'), table_name='external_reconciliations')
    op.drop_index('ix_external_reconciliations_ext_op_status', table_name='external_reconciliations')
    op.drop_index('ix_external_reconciliations_ext_attempt_id', table_name='external_reconciliations')
    op.drop_table('external_reconciliations')
    op.drop_index(op.f('ix_external_attempt_events_id'), table_name='external_attempt_events')
    op.drop_table('external_attempt_events')
    op.drop_index(op.f('ix_external_attempts_id'), table_name='external_attempts')
    op.drop_table('external_attempts')
    op.drop_index('ix_background_jobs_transaction_id', table_name='background_jobs')
    op.drop_index('ix_background_jobs_status_next', table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_id'), table_name='background_jobs')
    op.drop_index('ix_background_jobs_ext_op_id', table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_index(op.f('ix_external_operations_idempotency_key'), table_name='external_operations')
    op.drop_index(op.f('ix_external_operations_id'), table_name='external_operations')
    op.drop_table('external_operations')
    op.drop_index(op.f('ix_claim_items_id'), table_name='claim_items')
    op.drop_index(op.f('ix_claim_items_claim_id'), table_name='claim_items')
    op.drop_table('claim_items')
    op.drop_index(op.f('ix_transaction_items_id'), table_name='transaction_items')
    op.drop_table('transaction_items')
    op.drop_index(op.f('ix_integration_events_id'), table_name='integration_events')
    op.drop_table('integration_events')
    op.drop_index(op.f('ix_fwa_results_id'), table_name='fwa_results')
    op.drop_table('fwa_results')
    op.drop_index(op.f('ix_code_mappings_id'), table_name='code_mappings')
    op.drop_table('code_mappings')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index('ix_claims_hospital_status', table_name='claims')
    op.drop_index('ix_claims_hospital_created', table_name='claims')
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_adjudications_id'), table_name='adjudications')
    op.drop_table('adjudications')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_price_benchmarks_id'), table_name='price_benchmarks')
    op.drop_table('price_benchmarks')
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_hospital_codes_id'), table_name='hospital_codes')
    op.drop_table('hospital_codes')
    op.drop_index(op.f('ix_facility_users_id'), table_name='facility_users')
    op.drop_table('facility_users')
    op.drop_index(op.f('ix_coverage_rules_id'), table_name='coverage_rules')
    op.drop_table('coverage_rules')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_terminology_systems_id'), table_name='terminology_systems')
    op.drop_table('terminology_systems')
    op.drop_index(op.f('ix_patients_patient_reference'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_hospital_code'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_fwa_rules_id'), table_name='fwa_rules')
    op.drop_table('fwa_rules')
    op.drop_index(op.f('ix_common_codes_id'), table_name='common_codes')
    op.drop_index(op.f('ix_common_codes_common_code'), table_name='common_codes')
    op.drop_table('common_codes')
    op.drop_index(op.f('ix_commercial_policies_policy_number'), table_name='commercial_policies')
    op.drop_index(op.f('ix_commercial_policies_id'), table_name='commercial_policies')
    op.drop_table('commercial_policies')
    # ### end Alembic commands ###
