"""integration updates

Revision ID: fe81707939d6
Revises: 9bba7b8fe2a0
Create Date: 2026-09-10 12:35:20.409208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe81707939d6'
down_revision: Union[str, None] = '9bba7b8fe2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('response_endpoint', sa.String(length=500), nullable=True))
    op.add_column('hospitals', sa.Column('api_key_hash', sa.String(length=255), nullable=True))
    op.drop_index('ix_transactions_transaction_id', table_name='transactions')
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_unique_constraint('uq_hospital_transaction', 'transactions', ['hospital_id', 'transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_hospital_transaction', 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.create_index('ix_transactions_transaction_id', 'transactions', ['transaction_id'], unique=True)
    op.drop_column('hospitals', 'api_key_hash')
    op.drop_column('hospitals', 'response_endpoint')
    # ### end Alembic commands ###
